---
- name: Install | Ensure core packages are installed
  package:
    name: "{{ install_corepackages }}"
    state: present
  become: true

- name: Install | Ensure specified packages are installed
  package:
    name: "{{ install_packages }}"
    state: present
  become: true
