---
# handlers file for base_role
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  become: true

- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: true